***Exception handling in Python***
  
- Here the function output will terminate the flow of program if num satisfies the condition of exception which will cause the test case to fail

- To improvise the flow of execution exception can be handled with Try and except statements in the Output() function
